/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Advanced settings": {                           "en": "Advanced settings",                               "de": "Erweiterte Einstellungen",                        "ru": "Расширенные настройки",                           "pt": "Configurações avançadas",                         "nl": "Geavanceerde instellingen",                       "fr": "Réglages avancés",                                "it": "Impostazioni avanzate",                           "es": "Ajustes avanzados",                               "pl": "Zaawansowane ustawienia",                         "zh-cn": "高级的设置"},
    "Be sure your device is not in standby mode.": { "en": "Be sure your device is not in standby mode.",     "de": "Stellen Sie sicher, dass sich Ihr Gerät nicht im Standby-Modus befindet.", "ru": "Убедитесь, что ваше устройство не находится в режиме ожидания.", "pt": "Certifique-se de que seu dispositivo não esteja no modo de espera.", "nl": "Zorg ervoor dat uw apparaat niet in de standby-modus staat.", "fr": "Assurez-vous que votre appareil n'est pas en mode veille.", "it": "Assicurati che il tuo dispositivo non sia in modalità standby.", "es": "Asegúrese de que su dispositivo no esté en modo de espera.", "pl": "Upewnij się, że urządzenie nie znajduje się w trybie gotowości.", "zh-cn": "可以肯定你的设备不是处于待机模式。"},
    "Found devices": {                               "en": "Found devices",                                   "de": "Gefundene Geräte",                                "ru": "Найденные устройства",                            "pt": "Dispositivos encontrados",                        "nl": "Gevonden apparaten",                              "fr": "Appareils trouvés",                               "it": "Dispositivi trovati",                             "es": "Dispositivos encontrados",                        "pl": "Znaleziono urządzenia",                           "zh-cn": "设备找到了"},
    "IP-Address": {                                  "en": "IP Address",                                      "de": "IP Adresse",                                      "ru": "IP адрес",                                        "pt": "Endereço de IP",                                  "nl": "IP adres",                                        "fr": "Adresse IP",                                      "it": "Indirizzo IP",                                    "es": "Dirección IP",                                    "pl": "Adres IP",                                        "zh-cn": "IP地址"},
    "IP-Address of your AVR": {                      "en": "IP Address of your AVR",                          "de": "IP-Adresse Ihres AVRs",                           "ru": "IP адрес вашего AVR",                             "pt": "Endereço IP do seu AVR",                          "nl": "IP-adres van uw AVR",                             "fr": "Adresse IP de votre AVR",                         "it": "Indirizzo IP del tuo AVR",                        "es": "Dirección IP de su AVR",                          "pl": "Adres IP twojego AVR",                            "zh-cn": "IP地址你AVR"},
    "Interval between commands (ms)": {              "en": "Interval between commands (ms)",                  "de": "Intervall zwischen Befehlen (ms)",                "ru": "Интервал между командами (мс)",                   "pt": "Intervalo entre comandos (ms)",                   "nl": "Interval tussen opdrachten (ms)",                 "fr": "Intervalle entre les commandes (ms)",             "it": "Intervallo tra i comandi (ms)",                   "es": "Intervalo entre comandos (ms)",                   "pl": "Interwał między poleceniami (ms)",                "zh-cn": "之间的间隔的命令(ms)"},
    "Nothing found": {                               "en": "Nothing found",                                   "de": "Kein Gerät gefunden",                             "ru": "Ничего не найдено",                               "pt": "Nada encontrado",                                 "nl": "Niets gevonden",                                  "fr": "Rien n'a été trouvé",                             "it": "Non abbiamo trovato nulla",                       "es": "Nada Encontrado",                                 "pl": "Nic nie znaleziono",                              "zh-cn": "没有什么发现"},
    "Poll interval (ms)": {                          "en": "Poll interval (ms)",                              "de": "Abrufintervall (ms)",                             "ru": "Интервал опроса (мс)",                            "pt": "Intervalo de pesquisa (ms)",                      "nl": "Poll-interval (ms)",                              "fr": "Intervalle de sondage (ms)",                      "it": "Intervallo di polling (ms)",                      "es": "Intervalo de encuesta (ms)",                      "pl": "Interwał ankiety (ms)",                           "zh-cn": "投票时间间隔(ms)"},
    "Search": {                                      "en": "Search",                                          "de": "Suche",                                           "ru": "Поиск",                                           "pt": "Pesquisa",                                        "nl": "Zoeken",                                          "fr": "Chercher",                                        "it": "Ricerca",                                         "es": "Buscar",                                          "pl": "Szukaj",                                          "zh-cn": "搜索"},
    "Select one": {                                  "en": "Select one",                                      "de": "Wähle ein Gerät",                                 "ru": "Выбери один",                                     "pt": "Selecione um",                                    "nl": "Kies een",                                        "fr": "Sélectionnez un",                                 "it": "Seleziona uno",                                   "es": "Seleccione uno",                                  "pl": "Wybierz jeden",                                   "zh-cn": "选择一个"},
};